### ISSUE TITLE
standardreferencenumber ignored in query

### ISSUE THREAD

**Issue by ewg118** [harvardartmuseums/api-docs#1]
I have attempted to query coins by the standardreferencenumber field, but the field has no affect on the queries. I have tried RRC* as per Lucene syntax as well as "RRC 20/1"

**Comment by jeffsteward** [comment]
The standardreferencenumber is only searchable via the general **q** parameter. The field is indexed as follows so for the time being it only finds exact matches.
`
"standardreferencenumber" : {
        "type" : "string",
        "index" : "not_analyzed",
        "norms" : {
          "enabled" : false
        },
        "index_options" : "docs"
 }
`
Here is an example. 

`q=standardreferencenumber:"Padon%201"`

Can you post an one of your queries?

**Comment by ewg118** [comment]
Okay, that makes sense. There is still an issue with the query syntax:

http://api.harvardartmuseums.org/object?q=standardreferencenumber:"RRC 20/1"&apikey= works (1 result) and http://api.harvardartmuseums.org/object?q=standardreferencenumber:RRC*&apikey= does not (0 results). Since standardreferencenumber is indexed as a string rather than text, I would assume RRC* should find matches.

**Comment by jeffsteward** [comment]
RRC* searches won't work in the current implementation for two reasons. The field is set to be stored as non_analyzed and the field value pairs from the **q** parameters are passed in to a query_string query.

**Comment by ewg118** [comment]
Please let me know if you plan to reindex standardreferencenumber. The standard reference number for a coin is the singlemost important field in a numismatic database. I may have to harvest all of your coins and parse the reference fields one by one to find matches for RRC and RIC.

**Comment by jeffsteward** [comment]
Standardreferencenumer is now indexed in two forms. By default the field is indexed with the standard analyzer meaning you can now run queries like `q=standardreferencenumber:RRC` to find partial matches. The field is also indexed to support exact matches which take the form `q=standardreferencenumber:"Padon%201"`. Here is the mapping for the field.

```json
"standardreferencenumber" : {
    "type" : "string",
    "fields" : {
          "exact" : {
            "type" : "string", 
            "index" : "not_analyzed",
            "norms" : {
              "enabled" : false
            },
            "index_options" : "docs"
        }
    }
}
```

**Comment by ewg118** [comment]
Thanks!
