### ISSUE TITLE
Randomly receiving 'null' values

### ISSUE THREAD

**Issue by epignosis567** [harvardartmuseums/api-docs#14]
I randomly receive responses with null values when other times they have a value. 
For example, a query of the first 10 records of objects randomly assigns record 9's primaryimageurl as null even though it usually populates with a url. Very strange. Any ideas?

**Comment by epignosis567** [comment]
Sorry I didn't realize that the records in the response are semi-randomized each time they are called. It seems like the same 10 records are just jumbled in the array order each time. Is that normal?

**Comment by epignosis567** [comment]
Actually that's only part of the issue. The API definitely returning weird values.
![Screen Shot 2020-12-16 at 12 26 34 PM](https://user-images.githubusercontent.com/53028494/102383989-2bf63000-3f9a-11eb-8920-177512519acb.png)

**Comment by jeffsteward** [comment]
Can you post your API query parameters? I'll run a few tests on our end.

**Comment by epignosis567** [comment]
Thanks, but I think this was an error on my end. I was still getting thrown by the array getting randomized on each call. I think I've got it working now but I'll do some more testing and post back.
