### ISSUE TITLE
Getting multiple objects using objectnumber query

### ISSUE THREAD

**Issue by beahuang** [harvardartmuseums/api-docs#3]
I can get an object using a reference number like http://api.harvardartmuseums.org/object?apikey=xxx&objectnumber=BR41.37 but i'm not sure how to pass in multiple terms. The docs say I can pass in 1 or more terms. Can you tell me how I should format that?

**Comment by jeffsteward** [comment]
The current syntax is a bit problematic and will give you fuzzy results. You can try either separating your numbers by " OR " or use a trailing wildcard. 

objectnumber=BR41.36 OR BR41.37 OR BR41.38

objectnumber=BR41.*

I'm looking for suggestions on how to improve the usability of this filter in case you have any.
