### ISSUE TITLE
Request list of images with an associated artist

### ISSUE THREAD

**Issue by ataulm** [harvardartmuseums/api-docs#5]
I'm looking to query the `object` API for objects:

- that are paintings (`classification=26`
- has an image (`hasimage=1`)
- has an associated artist

The last one I'm currently filtering locally, by checking:

- if there is an array of persons (`people`)
- with at least one item where the person `role` == `"Artist"`

Is it possible to do this at the API level with `q`?

**Comment by jeffsteward** [comment]
You can do part of it with the `q` parameter and part of it with the `person` parameter.

Add these filters to your request:
- person=any
- q=people.role:Artist

**Comment by ataulm** [comment]
Excellent, thanks Jeff!
