### ISSUE TITLE
object and object/id return different values sometimes

### ISSUE THREAD

**Issue by ataulm** [harvardartmuseums/api-docs#6]
The value for `primaryimageurl` and the value of `images` is different for the same object ID when using the `object` endpoint vs. the `object/ID` endpoint.

It doesn't break for all objects, but it does for some. Below are two examples.

Both `142914` and `143495` have non-empty `images` arrays, and `primaryimageurl` is non-null when using `object/`.

When using `object/142914`, `primaryimageurl` is null and `images` is empty.
When using `object/143495`, `primaryimageurl` and `images` is as expected (with values).

Is this a bug in the backend?

**Comment by jeffsteward** [comment]
Thanks for the details. I'm not entirely sure where the bug is yet. Please post the parameters (excluding your API key) you are using with the `object` endpoint.

**Comment by ataulm** [comment]
Is this easy to read for the parameters?

```
@GET("object?$PAINTINGS_&$WITH_IMAGES_&$WITH_ARTIST_&$INC_FIELDS")
fun paintings(): Deferred<ApiPaintingsResponse>

@GET("object/{object_id}?$INC_FIELDS")
fun painting(@Path("object_id") id: String): Deferred<ApiRecord>

companion object {
    const val ENDPOINT = "https://api.harvardartmuseums.org"
    private const val PAINTINGS_ = "classification=26"
    private const val WITH_IMAGES_ = "hasimage=1"
    private const val WITH_ARTIST_ = "q=people.role:Artist"
    private const val INC_FIELDS = "fields=id,title,description,primaryimageurl,people"
}
```

So the `paintings` call is 👌 All the images are paintings, and they all have `primaryimageurl` and an `artist`.

For some of these, when I do the `painting(id)` call, the `images` array is empty and `primaryimageurl` is `null`.

**Comment by jeffsteward** [comment]
Yes. Thanks for the details. I can reproduce the issue and determined that part of this is a bug.

The `images` array and `primaryimageurl` should always be blank for records when a third party holds the copyright to those images. The behavior of those fields is now consistent between the `object` endpoint and the `object/ID` endpoint. 

Set the `q` parameter to `people.role:Artist AND imagepermissionlevel:0` to fetch objects with no copyright issues.

**Comment by ataulm** [comment]
Nice one, thanks for the adjusted params! I'll let you close this/leave it open as you like.
